name: Push Bucketeer image to Amazon ECR
run-name: Pushing Bucketeer image - new commit to master branch by ${{ github.actor }}
on:
  push:
    branches: master

jobs:
  docker:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3.6.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: login
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.ECR_REGI_ADDRESS }}
          username: ${{ secrets.ECR_REGI_USER }}
          password: ${{ secrets.ECR_REGI_PASS }}

      - name: Build and push
        id: buildpush
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.ECR_REGI_ADDRESS }}/dpop/bucketeer:v1-test
